import{i as l,S as c}from"./assets/vendor-gf4A_djT.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const d="46595467-38d51347a919535f7c3759bfb";function u(s){const n=`https://pixabay.com/api/?key=${d}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(n).then(e=>e.json()).then(e=>e.hits).catch(e=>(console.error("Error:",e),[]))}function f(s){const n=document.getElementById("image-gallery");n.innerHTML="",s.forEach(e=>{const r=document.createElement("a");r.href=e.largeImageURL,r.classList.add("gallery-item"),r.innerHTML=`
      <img src="${e.webformatURL}" alt="${e.tags}">
      <div class="image-info">
        <p><strong>Downloads:</strong> ${e.downloads}</p>
        <p><strong>Likes:</strong> ${e.likes}</p>
        <p><strong>Views:</strong> ${e.views}</p>
        
      </div>
    `,n.appendChild(r)})}function g(){const s=document.getElementById("image-gallery");s.innerHTML=""}const i=document.createElement("div");i.classList.add("loader");i.innerHTML='<div class="lds-dual-ring"></div>';document.body.appendChild(i);i.style.display="none";document.addEventListener("DOMContentLoaded",function(){let s;document.getElementById("search-button").addEventListener("click",async function(){const n=document.getElementById("search-input"),e=n.value;if(e===""){l.error({title:"Error",message:"Please enter a search query!"});return}g(),i.style.display="block";try{const r=await u(e);r.length>0?(f(r),s?s.refresh():s=new c(".gallery a",{captionsData:"alt",captionDelay:250})):l.error({title:"Error",message:"Sorry, no images matching your search query. Please try again!"})}catch(r){l.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error("Error:",r)}finally{i.style.display="none",n.value=""}})});
//# sourceMappingURL=index.js.map
