import{i as l,S as c}from"./assets/vendor-gf4A_djT.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const d="46595467-38d51347a919535f7c3759bfb";function u(o){const s=`https://pixabay.com/api/?key=${d}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(s).then(t=>t.json()).then(t=>t.hits).catch(t=>(console.error("Error:",t),[]))}function f(o){const s=document.getElementById("image-gallery");s.innerHTML="",o.forEach(t=>{const n=document.createElement("a");n.href=t.largeImageURL,n.classList.add("gallery-item"),n.innerHTML=`
      <img src="${t.webformatURL}" alt="${t.tags}">
      <div class="image-info">
        <p><strong>Downloads:</strong> ${t.downloads}</p>
        <p><strong>Likes:</strong> ${t.likes}</p>
        <p><strong>Views:</strong> ${t.views}</p>
        
      </div>
    `,s.appendChild(n)})}function m(){const o=document.getElementById("image-gallery");o.innerHTML=""}const i=document.createElement("div");i.classList.add("loader");i.innerHTML='<div class="lds-dual-ring"></div>';document.body.appendChild(i);i.style.display="none";document.addEventListener("DOMContentLoaded",function(){let o;document.querySelector(".search-container form").addEventListener("submit",async function(t){t.preventDefault();const n=document.getElementById("search-input"),e=n.value.trim();if(e===""){l.error({title:"Error",message:"Please enter a valid search query!"});return}m(),i.style.display="block";try{const r=await u(e);r.length>0?(f(r),o?o.refresh():o=new c(".gallery a",{captionsData:"alt",captionDelay:250})):l.error({title:"Error",message:"Sorry, no images matching your search query. Please try again!"})}catch(r){l.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error("Error:",r)}finally{i.style.display="none",n.value=""}})});
//# sourceMappingURL=index.js.map
